development:
  adapter: postgresql
  encoding: unicode
  database: disentanglar
  pool: 5
  username: 
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: disentanglar
  pool: 5
  username:
  password: 1234